'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class vmmc1

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClientnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientnumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_txtClientnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtClientnumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtVisitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVisitDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVMMCNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVMMCNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RequiredFieldValidatortxtVisitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatortxtVisitDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cmpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RegularExpressionValidator_txtVisitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_txtVisitDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblIRDOReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRDOReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFacilityDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilityDistrict As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVMMCNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVMMCNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDistrictCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrictCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTemp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFacilityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilityCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientUniqCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientUniqCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUniversalNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUniversalNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFacilityNameHid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityNameHid As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtFacilitySubLocHid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySubLocHid As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtFacilityDistrictHid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityDistrictHid As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtFacilityCountryHid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityCountryHid As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lblDistrictCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrictCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFacilityRegNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityRegNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredFieldValidator_txtFacilityRegNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtFacilityRegNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtFacilityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredFieldValidator_txtFacilityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtFacilityName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ctlContentPlaceHolder_DeliveryType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlContentPlaceHolder_DeliveryType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator_DeliveryType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_DeliveryType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtFacilityVillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityVillage As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredtxtFacilityVillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredtxtFacilityVillage As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtFacilitySubLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySubLoc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFacilityDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFacilityCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityCountry As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddClientNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddClientNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtA1_ClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA1_ClientName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtA2_ClientAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA2_ClientAge As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtA3_ClientPhoneContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA3_ClientPhoneContact As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtA4_ClientVillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA4_ClientVillage As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtA4_ClientResidenceDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA4_ClientResidenceDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtA4_ClientResidenceSubLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA4_ClientResidenceSubLoc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtA4_ClientResidenceCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA4_ClientResidenceCounty As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddA5_InfoSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddA5_InfoSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtA5_InfoSourceOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtA5_InfoSourceOther As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddB1_FacResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB1_FacResult As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddB1_SelfResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB1_SelfResult As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddB1_PartResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB1_PartResult As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddB1_CounsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB1_CounsName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtB1_CounsDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB1_CounsDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_txtB1_CounsDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtB1_CounsDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CompCounsDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompCounsDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RegularExpressionValidator_txtB1_CounsDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_txtB1_CounsDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ddB2_BleedDis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB2_BleedDis As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB2_BleedDis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB2_BleedDis As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB3_UrethDisch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB3_UrethDisch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB3_UrethDisch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB3_UrethDisch As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB3_Gensore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB3_Gensore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB3_Gensore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB3_Gensore As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB3_PainUrine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB3_PainUrine As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB3_PainUrine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB3_PainUrine As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB3_ScrotSwell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB3_ScrotSwell As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB3_ScrotSwell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB3_ScrotSwell As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB3_RectractfSkin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB3_RectractfSkin As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB3_RectractfSkin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB3_RectractfSkin As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB3_ReturnfSkin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB3_ReturnfSkin As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB3_ReturnfSkin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB3_ReturnfSkin As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB3_Erection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB3_Erection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB3_Erection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB3_Erection As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtB3_OtherSpecify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB3_OtherSpecify As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddB4_Anaemia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB4_Anaemia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB4_Anaemia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB4_Anaemia As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB4_Diabetes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB4_Diabetes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB4_Diabetes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB4_Diabetes As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddB4_HIVAids control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB4_HIVAids As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB4_HIVAids control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB4_HIVAids As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtB4_OtherSpecify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB4_OtherSpecify As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddB5_Allergy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB5_Allergy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB5_Allergy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB5_Allergy As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtB5_OtherSpecify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB5_OtherSpecify As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddB6_Surgical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddB6_Surgical As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddB6_Surgical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddB6_Surgical As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtB6_OtherSpecify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB6_OtherSpecify As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtB7_BP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB7_BP1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredtxtB7_BP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredtxtB7_BP1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Range_B7_BP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Range_B7_BP1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtB7_BP2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB7_BP2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredtxtB7_BP2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredtxtB7_BP2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RangeValidator_txtB7_BP2_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator_txtB7_BP2_ As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtB7_Pulse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB7_Pulse As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredtxtB7_Pulse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredtxtB7_Pulse As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RangetxtB7_Pulse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxtB7_Pulse As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtB7_Weight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB7_Weight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredtxtB7_Weight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredtxtB7_Weight As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Range_txtB7_Weight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Range_txtB7_Weight As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtB7_Temperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtB7_Temperature As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredtxtB7_Temperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredtxtB7_Temperature As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RangetxtB7_Temperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxtB7_Temperature As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ddC1_Health control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddC1_Health As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddC1_Health control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddC1_Health As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddC2_Counseled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddC2_Counseled As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddC2_Counseled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddC2_Counseled As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddC3_Consent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddC3_Consent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredddC3_Consent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredddC3_Consent As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtC3_Explain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtC3_Explain As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''pnl_MCProcedure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_MCProcedure As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtD1_MC_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD1_MC_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ComptxtD1_MC_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComptxtD1_MC_Date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''CompatxtD1_MC_Date1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompatxtD1_MC_Date1 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RegulartxtD1_MC_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegulartxtD1_MC_Date As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txD2_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txD2_StartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangetxD2_StartTimehh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxD2_StartTimehh As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txD2_StartTime2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txD2_StartTime2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangetxD2_StartTime2MM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxD2_StartTime2MM As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txD3_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txD3_EndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangetxD3_EndTime2HH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxD3_EndTime2HH As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txD3_EndTime2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txD3_EndTime2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangetxD3_EndTime2MM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxD3_EndTime2MM As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuration As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblD2_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblD2_StartTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblD3_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblD3_EndTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtD2_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD2_StartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtD3_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD3_EndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddD4_OPMedCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD4_OPMedCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddD5_Anaesthesia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD5_Anaesthesia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddD5_Concentration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD5_Concentration As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtD5_Volume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD5_Volume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtD5_SpecifyOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD5_SpecifyOther As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddD6_Procedure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD6_Procedure As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtD6_SpecifyOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD6_SpecifyOther As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddD7_AEDuring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD7_AEDuring As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddD7_AEType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD7_AEType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddD9_AESeverity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD9_AESeverity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddD10_Surgname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD10_Surgname As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtD11_SurgCadre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD11_SurgCadre As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddD12_AssSurgname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddD12_AssSurgname As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtD13_CadreAssSurg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD13_CadreAssSurg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtE1_BP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtE1_BP As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RangetxtE1_BP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxtE1_BP As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtE1_BP2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtE1_BP2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Range_txtE1_BP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Range_txtE1_BP As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtE1_Pulse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtE1_Pulse As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RangetxtE1_Pulse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxtE1_Pulse As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''txtE1_Temperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtE1_Temperature As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RangetxtE1_Temperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangetxtE1_Temperature As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ddE2_Medication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddE2_Medication As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddE3_PostInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddE3_PostInstruction As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddE4_Dis_OfficerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddE4_Dis_OfficerName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtE5_CadreAssSurg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtE5_CadreAssSurg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdFolloup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdFolloup As Global.System.Web.UI.WebControls.Button
End Class
