'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registration

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientUniqCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientUniqCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDistricCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistricCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblClientIDPad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientIDPad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFacilityDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddPersonDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPersonDistrict As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRegDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidatortxtRegDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatortxtRegDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cmpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RegularExpressionValidator_txtRegDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_txtRegDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtClientNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredFieldValidatortxtClientNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatortxtClientNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblIRDOReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRDOReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfIRDOReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIRDOReference As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtIRDOReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIRDOReference As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblDistricCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistricCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRDOINT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRDOINT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredtxtAuditDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredtxtAuditDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtOthernames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOthernames As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredFieldValidator_txtOthernames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_txtOthernames As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOB As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CompaDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompaDOB As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''ComptxtDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComptxtDOB As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAge As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredFieldValidatortxtAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatortxtAge As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddgender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddgender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidatorddgender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddgender As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidatorddLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddLocation As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddDivision As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidatorddDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddDivision As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RequiredFieldValidatorddDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddDistrict As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddNearestHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddNearestHF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidatorddNearestHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddNearestHF As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtPhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddEducatLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddEducatLevel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidatorddEducatLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddEducatLevel As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddReligion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelOther As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddMaritalStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidatorddMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddMaritalStatus As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddRecruitingIntv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddRecruitingIntv As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidatorddRecruitingIntv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorddRecruitingIntv As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCardIssuer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCardIssuer As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button
End Class
